site_title: Contigo
site_description: An East Austin restaurant modeled after our family's Texas ranch.
social:
  instagram: https://instagram.com/contigoaustin
banner:
  show_banner: true
  banner_copy: Test Announcement for Contigo.
  banner_link: ""
  banner_style: default
reservations_widget: <script type='text/javascript'
  src='//www.opentable.com/widget/reservation/loader?rid=83281&type=button&theme=standard&iframe=false&domain=com&lang=en-US&newtab=false&ot_source=Restaurant%20website'></script>
order_link: https://www.toasttab.com/contigo-austin/v3
gift_cards: https://www.toasttab.com/contigo-austin/giftcards
location: 2027 Anchor Lane, Austin, TX 78723
phone: (512) 614-2260
emails:
  - email: info@contigoaustin.com
  - email: events@contigoaustin.com
