---
site_title: "Contigo"
site_description: "An East Austin restaurant modeled after our family's Texas ranch."
banner:
  show_banner: false
  banner_copy: ""
  banner_link: ""
reservations_widget: '<div id="Tock_widget_container" data-tock-display-mode="Button" data-tock-color-mode="White" data-tock-locale="en-us" data-tock-timezone="America/Chicago"></div>'
order_link: "https://www.toasttab.com/contigo-austin/v3"
gift_cards: "https://www.toasttab.com/contigo-austin/giftcards"