site_title: Kerlaches
site_description: The best bbq-stuffed Kolaches in Texas.
ga:
social:
  instagram: https://instagram.com/kerlaches
banner:
  show_banner: false
  banner_copy: ""
  banner_link: ""
  banner_style: ""
order_link:
gift_cards:
contact_info:
  address: "2505 Webberville Rd"
  city: "Austin"
  state: "TX"
  zipcode: "78702"
emails:
  - email: info@kerlachesaustin.com
  - email: contact@kerlachesaustin.com