site_url: https://contigotexas.com
display_url: https://contigotexas.com
search: false

backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/_includes/assets/media"
public_folder: "/assets/media"
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: Homepage
    identifier_field: name
    extension: md
    format: yaml-frontmatter
    name: "homepage"
    files:
      - label: "Home"
        name: "home"
        file: "src/index.md"
        fields:
          - label: "Slideshow Gallery"
            name: "slider"
            allow_add: true
            widget: list
            fields:
              - label: "Image"
                name: "gallery_image"
                widget: image
                media_library:
                  config:
                    multiple: false
                    imagesOnly: true
              - label: "Image Description"
                name: "alt"
                widget: string
          - label: "Introduction"
            name: "site_intro"
            widget: "object"
            fields:
              - { label: "Subhead", name: "subhead", widget: string }
              - { label: "Content", name: "content", widget: markdown }
          - label: "Content Cards"
            name: "cards"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Content", name: "content", widget: markdown }
              - label: "Image"
                name: "card_image"
                widget: image
              - label: "Image Description"
                name: alt
                widget: string
              - label: "Image Placement"
                name: "image_style"
                widget: select
                options: [ "Left", "Right" ]
          - label: "Content Columns"
            name: "column_cards"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Content", name: "content", widget: markdown }
              - label: "Image"
                name: "card_image"
                widget: image
              - label: "Image Description"
                name: alt
                widget: string
          - label: "Grid Gallery"
            name: "grid"
            widget: "list"
            allow_add: true
            fields:
              - label: "Image"
                name: "gallery_image"
                widget: image
                media_library:
                  config:
                    multiple: false
                    imagesOnly: true
              - label: "Image Description"
                name: "alt"
                widget: string
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Global Settings"
        name: "details"
        file: "src/_data/settings.yaml"
        fields:
          - { label: "Site Title", name: site_title, widget: string }
          - { label: "SEO Description", name: site_description, widget: text }
          - label: "Social Media"
            name: social
            widget: object
            fields:
              - { label: "Instagram  URL", name: instagram, required: false, widget: string }
              - { label: "Facebook URL", name: facebook, required: false, widget: string }
              - { label: "Twitter URL", name: twitter, required: false, widget: string }
          - label: "Announcement Banner"
            name: banner
            widget: object
            fields:
              - { label: "Show announcement banner", name: show_banner, widget: boolean }
              - { label: "Announcement Text", name: banner_copy, required: false, widget: string }
              - { label: "Announcement Link", name: banner_link, required: false, widget: string }
              - label: "Announcement Style"
                name: banner_style
                widget: select
                required: false
                options:
                  - { label: "Banner", value: "default" }
                  - { label: "Fullscreen", value: "full" }
          - { label: "Reservations Widget", name: "reservations_widget", widget: code, default_language: "html", output_code_only: true}
          - { label: "Online Ordering Link", name: "order_link", widget: string }
          - { label: "Gift Cards Link", name: "gift_cards", widget: string }
          - { label: Address, name: location, widget: string }
          - { label: "Phone Number", name: phone, widget: string }
      - label: "Restaurant Details"
        name: "restaurant"
        file: "src/_data/restaurant.yaml"
        fields:
          - label: "Buttons"
            name: "cta"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Button Label", name: "label", widget: "string" }
              - label: "Type"
                name: "action"
                widget: "select"
                options:
                  - { label: "Reservations", value: "reservations" }
                  - { label: "Order Online", value: "order" }
                  - { label: "Gift Cards", value: "gift-card" }
          - label: "Service Hours"
            name: "service_hours"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Service", name: "service", widget: "string" }
              - { label: "Hours", name: "hours", widget: "text" }
              - { label: "Upload Menu", name: "menu_file", widget: file, required: false }